<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<!-- 
<meta http-equiv="x-ua-compatible" content="ie=7" />
 -->
<title><?php echo $this->layout()->system_title;?></title>
<link href="/css/ui-lightness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link type="text/css" rel="stylesheet" href="/css/global.css?20140404" />
<link type="text/css" rel="stylesheet" href="/css/public/index.css?20140404" />
<script type="text/javascript">
</script>
<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/jquery-myProject.js"></script>
<script type="text/javascript" src="/js/jquery-myAjaxForm.js"></script>
<script type="text/javascript" src="/js/init.js"></script>

<link type="text/css" rel="stylesheet" href="/css/jquery.alerts.css" />
<script type="text/javascript" src="/js/jquery.alerts.js"></script>

<link type="text/css" rel="stylesheet" href="/js/chosen/chosen.min.css" />
<script type="text/javascript" src="/js/chosen/chosen.jquery.js"></script>

</head>
<body id="boxscroll2" style="padding-bottom:84px;">
<?php echo $this->layout()->content;?>
<script type="text/javascript" src="/js/jquery-cookie.js"></script>
	<script type="text/javascript" src="/js/jquery.form.js"></script>
	<script type="text/javascript" src="/js/jquery.pagination.js"></script>
	<script type="text/javascript" src="/js/mod.js"></script>
	<script type="text/javascript" src="/js/jquery.myLoading.js"></script>
</body>
</html>