<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->layout()->system_title;?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/css/tnt016.css" rel="stylesheet">
<script src="/js/jquery.min.js"></script>
<script src="/laydate/laydate.js"></script>
<script src="/js/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="/js/jquery.SuperSlide.2.1.1.js"></script>
<!-- 时间 -->
<link rel="stylesheet" href="/css/bootstrapDatepickr-1.0.0.css">
<script src="/js/bootstrap.min.js"></script>
<!--<script src="/js/bootstrapDatepickr-1.0.0.js"></script>-->
<!-- 时间 -->
<script src="/js/cnScript.js"></script>

<link href="/css/ui-lightness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-myProject.js"></script>
<script type="text/javascript" src="/js/jquery-myAjaxForm.js"></script>
<script type="text/javascript" src="/js/init.js"></script>

<link type="text/css" rel="stylesheet" href="/css/jquery.alerts.css" />
<script type="text/javascript" src="/js/jquery.alerts.js"></script>

<link type="text/css" rel="stylesheet" href="/js/chosen/chosen.min.css" />
<script type="text/javascript" src="/js/chosen/chosen.jquery.js"></script>

<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
</head>
<body class="Contentbox">
   
		
	<div class="wrapper">
	<?php echo $this->layout()->content;?>
    	
    </div>    	<!-- wrapper -->


    </div>    <!-- RightBody -->


</body>
<script type="text/javascript" src="/js/jquery-cookie.js"></script>
	<script type="text/javascript" src="/js/jquery.form.js"></script>
	<script type="text/javascript" src="/js/jquery.pagination.js"></script>
	<script type="text/javascript" src="/js/mod.js"></script>
	<script type="text/javascript" src="/js/jquery.myLoading.js"></script>
	<!--  <script type="text/javascript" src="/js/resizeHandler.js"></script>-->
</html>