<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->layout()->system_title;?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/css/layout.css" rel="stylesheet">
<script src="/js/jquery-1.11.3.min.js"></script>
<script src="/js/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="/js/jquery.SuperSlide.2.1.1.js"></script>
<script src="/js/duplicateElement.min.js"></script>
<!-- 时间 -->
<link rel="stylesheet" href="/css/bootstrapDatepickr-1.0.0.css">
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrapDatepickr-1.0.0.js"></script>
<!-- 时间 -->
<script src="/js/cnScript.js"></script>
<style>
ul li a{
	cursor: pointer;
}
</style>
</head>
<body>
    <div class="LeftMenuBox">
    	<div class="Menu_Main" id="boxscroll">
    		<div class="logo">
				<h1><a id="top1" href="javascript:void(0)"><img src="/images/logo.png" alt="" /></a></h1>
			</div>
			<h3 class="on"><em></em>订单管理</h3>
			<ul>
				<li><a id="firstli" class="curr" hreforginal="/order/order/create?quick=52">E速宝录单</a></li>
				<li><a hreforginal="/order/order/createfba?quick=54">FBA录单</a></li>
				<li><a hreforginal="/order/order/createdhl?quick=52">中速快件录单</a></li>
				<li><a hreforginal="/order/order/createtnt?quick=53">中速TNT录单</a></li>
				<li><a hreforginal="/order/order/import?quick=24">批量导入订单</a></li>
				<li><a hreforginal="/order/order-list/list?quick=39">订单管理</a></li>
				<li><a hreforginal="/order/label-print/index?quick=92">标签打印</a></li>
			</ul>

			<h3><em></em>运单管理</h3>
			<ul>
				<!--  <li><a hreforginal="/shipment/business/list?quick=87">运单查询</a></li>-->
				<li><a hreforginal="/default/index/get-track-detail?quick=76">订单追踪</a></li>
			</ul>
			<h3><em></em>账户设置</h3>
			<ul>
				<li><a hreforginal="/order/submiter/list?quick=77">发件人资料</a></li>
				<li><a hreforginal="/default/index/help?quick=96">操作手册</a></li>
				<li><a hreforginal="/auth/user/user-set?quick=79">密码修改</a></li>
				<li><a hreforginal="/auth/user/index?quick=2">用户中心</a></li>
			</ul>
		</div><!-- Menu_Main End -->

		<script type="text/javascript">
			jQuery(".Menu_Main").slide({titCell:"h3", targetCell:"ul", effect:"slideDown",delayTime:300 ,triggerTime:150 
				});
			$('li a').click(function(){
					var that= this;
					$("iframe").attr("src",$(this).attr('hreforginal'));
					$('li a').removeClass("curr");
					$(this).addClass("curr");/* 
					$("iframe")[0].onload=function(){
						var body=document.getElementById("resultFrame").contentWindow.document.getElementsByTagName('body');$(body).addClass("Contentbox");
					} */
				})
				
			$("#top1").click(function(){
				location.reload();	
			});	
		</script>
    	 <!-- Menu_Main -->

    </div>   <!-- LeftMenuBox -->
    
    <div class="right_container_iframe">
    <?php echo $this->action("header1","system","default");?>
    
        <iframe id="resultFrame" name="resultFrame" src="/order/order/create" marginheight="0" marginwidth="0" frameborder="0" scrolling="no" width="100%" height="100%" ></iframe>
    </div>


    

</body>
</html>