<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<!-- 
<meta http-equiv="x-ua-compatible" content="ie=7" />
 -->
<title><?php echo $this->layout()->system_title;?></title>
<link href="/css/ui-lightness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link type="text/css" rel="stylesheet" href="/css/global.css?20140404" />
<link type="text/css" rel="stylesheet" href="/css/public/index.css?20140404" />
<link type="text/css" rel="stylesheet" href="/css/public/layout.css?20140404" />
<link type="text/css" rel="stylesheet" href="/css/public/head.css?20140404" />

<style type="text/css">
.logo2{background-image:url("<?php echo $this->layout()->logo;?>");}
</style>
<script type="text/javascript">
//语言
var locale_message_language = '<?php echo $this->layout()->lang;?>';
</script>
<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/jquery-myProject.js"></script>
<script type="text/javascript" src="/js/jquery-myAjaxForm.js"></script>
<script type="text/javascript" src="/js/init.js?20160510"></script>
<script type="text/javascript" src="/js/locale/oms-lang-en_US.js"></script>
<script type="text/javascript" src="/js/locale/oms-lang-zh_CN.js"></script>
<script type="text/javascript" src="/js/locale/locale_message.js"></script>
<link type="text/css" rel="stylesheet" href="/js/chosen/chosen.min.css" />
<script type="text/javascript" src="/js/chosen/chosen.jquery.js"></script>

<link type="text/css" rel="stylesheet" href="/css/jquery.alerts.css" />
<script type="text/javascript" src="/js/jquery.alerts.js"></script>
</head>
<body>
<?php echo $this->action("header","system","default");?>
<div id="main-container">
		<div class="shrink">&nbsp;</div>
		<div class="main-right" id="main-right">
        <?php echo $this->action("right-guild","system","default");?>
        <div class="main-right-container" id="main-right-container-iframe">
				<iframe frameborder="0" src="/system/home" width="100%" height="100%" id="iframe-container-0" name="iframe-container-0" class="iframe-container"></iframe>
			</div>
		</div>
	</div>
	<script type="text/javascript" src="/js/jquery-cookie.js"></script>
	<script type="text/javascript" src="/js/jquery.form.js"></script>
	<script type="text/javascript" src="/js/jquery.pagination.js"></script>
	<script type="text/javascript" src="/js/mod.js"></script>
	<script type="text/javascript" src="/js/jquery.myLoading.js"></script>
</body>
</html>